config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :create]
  root "orders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates_presence_of :name, :email, :address
  has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @products = Product.all
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.products.map{|e| e.stock}.index(0).nil?
      @order.products.map{|e| e.stock-=1}
      if @order.save    
        flash[:notice] = "購買成功，訂購明細已發送至您的Email"
        UserMailer.notify_order_create(@order).deliver_now!
        redirect_to orders_path
      else
        flash[:alert] = "姓名、地址、Email不可空白"
        redirect_to orders_path
      end
    else
      flash[:alert] = "訂購失敗，選購的商品已售完"
      redirect_to orders_path
    end  
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :product_ids=>[])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mitorder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %> 
      <div class="alert alert-primary text-center alert-dismissible fade show mb-0" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if flash[:alert] %> 
      <div class="alert alert-primary text-center alert-dismissible fade show mb-0" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>
<script type="text/javascript">
  $( document ).ready(function() {
    setTimeout(function(){ $(".alert").hide() },2700)
  });
</script>

app/views/orders/index.html.erb
<div class="container p-3">
  <table class="table table-bordered text-center table-info">
    <thead class="thead-dark">
      <tr>    
        <th>商品名稱</th>
        <th>庫存量</th>
      </tr>
    </thead>  
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td>
            <% if product.stock == 0 %>
              <%= "sold out" %>
            <% else %>
              <%= product.stock %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= form_for @order ,url: orders_url do |f|%>
    選購<%= f.collection_check_boxes(:product_ids, Product.all, :id, :name) do |b| %>
         <%= b.label class:"p-4" do %>
          <%= b.check_box + b.text%>
         <% end %>
       <%end%>
    <div class="form-group">
      <%= f.label :name, "姓名"%>
      <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :email, "Email"%>
      <%= f.text_field :email, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :address, "地址"%>
      <%= f.text_field :address, class: "form-control"%>
    </div>
    <%= f.submit "成立訂單", class:"btn btn-primary"%>
  <%end%>
</div>